# Generated by Django 4.2.30 on 2026-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_session_detection_attendancesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_frames',
            field=models.IntegerField(default=0),
        ),
    ]
